### ISSUE TITLE
Wildcard router?

### ISSUE THREAD

**Issue by lexrus** [Zewo/Router#4]
I'd like to serve some static files(e.g. css/js) in ./Static folder. But looks like there's no wildcard pattern for such map. I need something like:

``` swift
router.get("/static/*") { request in
    let path = request.uri.path
    return Response(status: .OK, filePath: "./some_static_subfolder/\(path)")
}
```

Furthermore, it'll be awesome to have a regex match:

``` swift
router.re(.GET, "/images/NO[\\d]+\\.jpg") { request in
    if let number = request.re.match?.1 {
        return Response(status: .OK, filePath: "./images/\(number).jpg")
    } else {
        return Response(status: .NotFound)
}
```

**Comment by paulofaria** [comment]
Actually the Router already supports regex, but only POSIX regex. You can get the behaviour you want in a different way, which is in the example at github.com/Zewo/Examples. I'm on a trip now. When I get back I'll look into this more closely.

**Comment by lexrus** [comment]
I've read the code in Examples and fixed my router.
Thank you, Paul.
